### ISSUE TITLE
Doesn't seem vulnerable

### ISSUE THREAD

**Issue by maliade** [d3fudd/Xiongmai-Net-Surveillance-Authentication-Bypass#2]
![捕获](https://github.com/d3fudd/Xiongmai-Net-Surveillance-Authentication-Bypass/assets/94565579/e4c77424-c8e5-4710-9b2d-21f2715d6f45)

**Comment by d3fudd** [comment]
> ![捕获](https://user-images.githubusercontent.com/94565579/282608890-e4c77424-c8e5-4710-9b2d-21f2715d6f45.PNG)

So it doesn't seem vulnerable.
